const studentsList = [
  {
    image: "https://randomuser.me/api/portraits/men/71.jpg",
    id: 1,
    firstName: "sagar",
    lastName: "bhatt",
    dob: "11-02-1998",
    collegeName: "Gujarat Technological University",
    address: "Gandhinagar",
    collegeLogo: "./assets/img/college-logo-1.png",
  },
  {
    image: "https://randomuser.me/api/portraits/men/72.jpg",
    id: 2,
    firstName: "harsh",
    lastName: "bhatt",
    dob: "19-11-2008",
    collegeName: "Nirma University",
    address: "Gota",
    collegeLogo: "./assets/img/college-logo-1.png",
  },
  {
    image: "https://randomuser.me/api/portraits/men/73.jpg",
    id: 3,
    firstName: "niraj",
    lastName: "surati",
    dob: "19-11-2010",
    collegeName: "Nirma University",
    address: "Gota",
    collegeLogo: "./assets/img/college-logo-1.png",
  },
  {
    image: "https://randomuser.me/api/portraits/men/74.jpg",
    id: 4,
    firstName: "meet",
    lastName: "shah",
    dob: "19-11-2008",
    collegeName: "GMCA",
    address: "Khokhara",
    collegeLogo: "./assets/img/college-logo-1.png",
  },
  {
    image: "https://randomuser.me/api/portraits/men/75.jpg",
    id: 5,
    firstName: "harsh",
    lastName: "patel",
    dob: "19-11-2008",
    collegeName: "NGCCA",
    address: "Incometax",
    collegeLogo: "./assets/img/college-logo-1.png",
  },
];

export default studentsList;
